from loaia.actions.base import ActionDefinition

CALC_ACTIONS = [
    ActionDefinition(
        "Calc.GetSelectedRange",
        "calc",
        safe_formatting=False,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.GetSelectedFormula",
        "calc",
        safe_formatting=False,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.ToggleBold",
        "calc",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.ToggleItalic",
        "calc",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.AlignLeft",
        "calc",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.AlignCenter",
        "calc",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.AlignRight",
        "calc",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.ApplyNumberFormatCurrency",
        "calc",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.ApplyNumberFormatPercent",
        "calc",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.ApplyNumberFormatDate",
        "calc",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Calc.InsertFormulaInSelection",
        "calc",
        safe_formatting=False,
        requires_approval=True,
    ),
    ActionDefinition(
        "Calc.CreateChartFromSelection",
        "calc",
        safe_formatting=False,
        requires_approval=True,
    ),
    ActionDefinition(
        "Calc.SortSelectedRange",
        "calc",
        safe_formatting=False,
        requires_approval=True,
    ),
]
