from loaia.actions.base import ActionDefinition

DRAW_ACTIONS = [
    ActionDefinition(
        "Draw.GetSelectedText",
        "draw",
        safe_formatting=False,
        requires_approval=False,
    ),
    ActionDefinition(
        "Draw.ToggleBold",
        "draw",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Draw.ToggleItalic",
        "draw",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Draw.ToggleUnderline",
        "draw",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Draw.AlignLeft",
        "draw",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Draw.AlignCenter",
        "draw",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Draw.AlignRight",
        "draw",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Draw.ReplaceSelectedText",
        "draw",
        safe_formatting=False,
        requires_approval=True,
    ),
]
