from loaia.actions.base import ActionDefinition

WRITER_ACTIONS = [
    ActionDefinition(
        "Writer.GetSelection",
        "writer",
        safe_formatting=False,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.ToggleBold",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.ToggleItalic",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.ToggleUnderline",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.ApplyHeading1",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.ApplyHeading2",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.ApplyHeading3",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.ApplyBullets",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.AlignLeft",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.AlignCenter",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.AlignRight",
        "writer",
        safe_formatting=True,
        requires_approval=False,
    ),
    ActionDefinition(
        "Writer.ReplaceSelection",
        "writer",
        safe_formatting=False,
        requires_approval=True,
    ),
    ActionDefinition(
        "Writer.InsertBelowSelection",
        "writer",
        safe_formatting=False,
        requires_approval=True,
    ),
    ActionDefinition(
        "Writer.InsertTable",
        "writer",
        safe_formatting=False,
        requires_approval=False,
    ),
]
